apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fivetran-extra
  description: Extract data from S3 storage used by Fivetran
  tags:
    - python
spec:
  type: glue-job
  lifecycle: production
  owner: marketing-na
  system: salesforce-customers
