apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Fivetran Extract
  name: fivetran-extract
  description: Extract data from S3 storage used by Fivetran
  annotations:
    backstage.io/techdocs-ref: dir:./documents/component-ingest
  tags:
    - python
spec:
  type: glue-job
  lifecycle: production
  owner: marketing-na
  system: salesforce-customers
  dependsOn:
    - system:fivetran
