apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Customer Publish
  name: customer-publish
  description: Published processed data to Kafka.
  tags:
    - python
spec:
  type: glue-job
  lifecycle: production
  owner: marketing-na
  system: salesforce-customers
  dependsOn:
    - component:customer-enrichment
    - system:confluent-kafka
