apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Mulesoft Integration
  name: mulesoft-integration
  description: Consume data from Kafka topic and publish it into Salesforce.
  tags:
    - python
spec:
  type: on-premise
  lifecycle: production
  owner: marketing-na
  system: salesforce-customers
  dependsOn:
    - component:customer-publish
    - component:confluent-kafka
    - api:salesforce-api
